Homework3
Vena77/newNew pull request #3
Opened 2021-11-25 19:19 UTC by Vena77

homework3

2021-11-28 14:54 UTC, v-lozhkin requested changes

2021-11-28 14:54 UTC, v-lozhkin commented on homework2/ex1.go
> +package main
Не совсем понял, почему в этом реквесте задания из ДЗ №2

2021-11-28 14:54 UTC, v-lozhkin commented on homework3/w1.go
> +	fmt.Println("Введите второе число: ")
Второе число нужно не во всех случаях. Например, при взятии факториала, оно ни к чему

2021-11-28 14:54 UTC, v-lozhkin commented on homework3/w1.go
> +	case "_":
Я думаю тут все же нужно "-" (минус), а не "_" (нижнее подчеркивание)

2021-11-28 14:54 UTC, v-lozhkin commented on homework3/w1.go
> +		for i := 1; i < d; i++ {
Для возведение числа в степень можно использовать функцию .Pow() из пакета math

2021-11-28 14:54 UTC, v-lozhkin commented on homework3/w1.go
> +		fmt.Println(factorial(d))
Не нужно класть в отдельную переменную. Можно привести к анонимной переменной 
fmt.Println(factorial(uint(a))).

Однако даже так не будет работать при вводу отрицательного числа (паника). 
Нужно отдельно предусмотреть невозможность ввести отрицательное число

2021-11-28 14:54 UTC, v-lozhkin commented on homework3/w1.go
> +		if a+b == math.Trunc(a+b) {
Не очень хорошая идея строить логику программу в зависимости от необходимостей форматирования вывода. 
Лучше попробовать использовать "%.3g"

2021-11-30 13:12 UTC, Vena77 commented on homework3/w1.go
> +	case "_":
видимо я еще не совсем разобралась, как git работает

2021-11-30 13:13 UTC, Vena77 commented on homework3/w1.go
> +	fmt.Println("Введите второе число: ")
понятно, но в этом задании я решила не заострять на этом внимание и отдельно на это не было указано в задании.

2021-11-30 13:25 UTC, Vena77 commented on homework3/w1.go
> +		for i := 1; i < d; i++ {
ок, буду знать

2021-11-30 13:36 UTC, Vena77 commented on homework3/w1.go
> +		fmt.Println(factorial(d))
исправила

2021-11-30 13:53 UTC, Vena77 commented on homework3/w1.go
> +		if a+b == math.Trunc(a+b) {
ок. попробовала, не поняла, что выводит
приведите полный пример с умножением пожалуйста.

2021-11-30 16:28 UTC, v-lozhkin requested changes

2021-11-30 16:28 UTC, v-lozhkin commented on homework2/ex1.go
> +package main
а, просто нужно замержить прошлый мр

2021-11-30 16:28 UTC, v-lozhkin commented on homework3/w1.go
> +	fmt.Println("Введите второе число: ")
Надо бы все же предусмотреть

2021-11-30 16:28 UTC, v-lozhkin commented on homework3/w1.go
> +		for i := 1; i < d; i++ {
Надо бы поправить

2021-11-30 16:28 UTC, v-lozhkin commented on homework3/w1.go
> +			a = -a
незачем додумывать за пользователя. Достаточно просто вернуть ошибку

2021-11-30 16:28 UTC, v-lozhkin commented on homework3/w1.go
> +			fmt.Printf("%.2f \n", a-b)
На самом деле, моя ошибка. Исходя из описания задания g подходит не очень. 
Использовать %.2f - нормально, но не нужно разделять выводы целого и не целого числа. (то есть окей, если будет 3*4=12.00)

2021-12-04 13:22 UTC, v-lozhkin approved these changes
Принято

2021-12-04 13:53 UTC, merged