Homework4
Vena77/newNew pull request #4
Opened 2021-11-30 17:02 UTC by Vena77

2021-12-01 07:33 UTC, v-lozhkin requested changes
Нужно чуть-чуть причесать сортировку

2021-12-01 07:33 UTC, v-lozhkin commented on homework4/ex1.go
> +		_, err := fmt.Scanln(&a)
Не совсем понял проблему, описанную при сдаче ДЗ на платформе. 
В целом, сейчас здесь все правильно считывается

2021-12-01 07:33 UTC, v-lozhkin commented on homework4/ex1.go
> +		_, err := fmt.Scanln(&a)
Опишите, пожалуйста, тут подробнее, если есть необходимость в пояснении

2021-12-01 07:33 UTC, v-lozhkin commented on homework4/ex1.go
> +	//x := [10]int{3, 6, 9, 67, 0, 1, 4, 6, 8, 9}
кажется, комментарий тут ни к чему

2021-12-01 07:33 UTC, v-lozhkin commented on homework4/ex1.go
> +	//x := [10]int{3, 6, 9, 67, 0, 1, 4, 6, 8, 9}
Они обычно пишутся для пояснения некоторых моментов вашего кода.

2021-12-01 07:33 UTC, v-lozhkin commented on homework4/ex1.go
> +		y := x[i]
Можно обойтись без двух дополнительных переменных (y и ind), если использовать функцию го с двойным присваиванием для свопа элементов (было на втором уроке).
То есть, если вы хотите поменять местами x[i] и x[j], то нужно просто использовать x[i], x[j] = x[j], x[i]

2021-12-02 16:44 UTC, Vena77 commented on homework4/ex1.go
> +	//x := [10]int{3, 6, 9, 67, 0, 1, 4, 6, 8, 9}
исправила

2021-12-02 19:17 UTC, v-lozhkin approved these changes
Принято

2021-12-04 13:48 UTC, merged