homework6
Vena77/newNew pull request #7
Opened 2021-12-07 11:22 UTC by Vena77

2021-12-07 20:18 UTC, v-lozhkin requested changes

2021-12-07 20:18 UTC, v-lozhkin commented on homework6/ex2.txt
> +b. В функциях и методах?
Не совсем. Тут речь о слайсах и мапах, так как в их структуре уже заложен указатель

2021-12-07 20:18 UTC, v-lozhkin commented on homework6/ex1.go
> +	y := make([]Point, 0, 5)
Смысл связного списка как раз в том, чтобы узлы не хранились упорядоченно в какой-то структуре типа массива. Их связь работает именно за счет того, что каждый элемент указывает на другой

2021-12-07 20:18 UTC, v-lozhkin commented on homework6/ex1.go
> +		y[i].x, y[j].x = y[j].x, y[i].x
Сейчас это просто реализация разворота слайса

2021-12-08 11:41 UTC, Vena77 commented on homework6/ex1.go
> +	y := make([]Point, 0, 5)
Подскажите тогда, где или как сохранять значения , если я не знаю сколько их будет введено с клавиатуры. Например n1,n2,n3? как присобачивать цифру к очередной n в go? , я не знаю. Просьба, Вы не могли бы подсказывать варианты решений, я учусь и не до всего могу догадаться, как бы вам того не хотелось.

2021-12-11 12:48 UTC, v-lozhkin approved these changes
Принято

2021-12-13 12:16 UTC, merged